name: Docs

on:
  push:
    branches: 
      - main

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install 'compound_target_pairs_dataset[dev]'
      - name: Build documentation
        timeout-minutes: 5
        run: |
          cd docs
          make clean
          make html
      - name: Upload docs as artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  publish_docs:
    name: Publish docs
    needs: build_docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4