name: Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "documentation"
  documentation:
    # The type of runner that the job will run on
    runs-on: macos-latest-xlarge
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install 'compound_target_pairs_dataset[dev]'
      - name: Build documentation
        timeout-minutes: 5
        run: |
          cd docs
          make clean
          make html
      - name: Upload docs as artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html
