name: Lint

on: 
  push: 
    branches: 
      - main  
  pull_request:
      
jobs:
  lint:
    name: Lint (black + pylint)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install black pylint
    - name: Analyse the code with black
      run: |
        black src --check
    - name: Analyse the code with pylint
    # ignore grid tables when checking for long lines 
      run: |
        pylint src --ignored-modules rdkit --ignore-long-lines "^\s*(\+[\-\=]+)+\+|(?:\|.*)+\|"
